### ISSUE TITLE
按照docs/guide/getting_start.md里操作连接报错

### ISSUE THREAD

**Issue by talking-toaster** [richardchien/nonebot#106]
python bot.py
报错
ujson module not found, using json
msgpack not installed, MsgPackSerializer unavailable
[2019-10-24 21:12:15,784 nonebot] INFO: Succeeded to import "nonebot.plugins.base"
[2019-10-24 21:12:15,784 nonebot] INFO: Running on 127.0.0.1:8080
Running on https://127.0.0.1:8080 (CTRL + C to quit)
[2019-10-24 21:12:15,785] ASGI Framework Lifespan error, continuing without Lifespan support
[2019-10-24 21:12:15,786 nonebot] INFO: Scheduler started
Traceback (most recent call last):
  File "bot.py", line 6, in <module>
    nonebot.run(host='127.0.0.1', port=8080)
  File "E:\Python\lib\site-packages\nonebot\__init__.py", line 105, in run
    get_bot().run(host=host, port=port, *args, **kwargs)
  File "E:\Python\lib\site-packages\nonebot\__init__.py", line 54, in run
    super().run(host=host, port=port, *args, **kwargs)
  File "E:\Python\lib\site-packages\aiocqhttp\__init__.py", line 228, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "E:\Python\lib\site-packages\quart\app.py", line 1346, in run
    run_single(self, config, loop=loop)  # type: ignore
  File "E:\Python\lib\site-packages\hypercorn\asyncio\run.py", line 126, in run_single
    loop.run_until_complete(worker_serve(app, config))
  File "E:\Python\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "E:\Python\lib\site-packages\hypercorn\asyncio\run.py", line 144, in worker_serve
    sockets = config.create_sockets()
  File "E:\Python\lib\site-packages\hypercorn\config.py", line 206, in create_sockets
    sock.bind(binding)
OSError: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

处理：将data/app/io.github.richardchien.coolqhttpapi/config/里json文件改动"use_http": false,

**Comment by richardchien** [comment]
@talking-toaster 应该是端口冲突了吧，你是不是在 cqhttp 的 config 里也设置了 port 为 8080

**Comment by talking-toaster** [comment]
确实是端口冲突了，刚才没搞明白，cqhttp的config里设置的是5700，还在看是谁占用了
