### ISSUE TITLE
HTTP 连接 Python 后报错

### ISSUE THREAD

**Issue by nainiu233** [richardchien/nonebot#154]
报错内容如下：
Task exception was never retrieved
future: <Task finished coro=<worker_serve.<locals>._server_callback() done, defined at C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\asyncio\run.py:88> exception=AttributeError("'WSStream' object has no attribute 'connection'") created at C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\asyncio\streams.py:239>
source_traceback: Object created at (most recent call last):
  File "C:/Users/lpj15/Desktop/酷Q Air/awesome-bot/bot.py", line 13, in <module>
    nonebot.run()
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\nonebot\__init__.py", line 105, in run
    get_bot().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\nonebot\__init__.py", line 54, in run
    super().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\aiocqhttp\__init__.py", line 200, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\quart\app.py", line 1615, in run
    loop.run_until_complete(task)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 538, in run_forever
    self._run_once()
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 1774, in _run_once
    handle._run()
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\asyncio\streams.py", line 239, in connection_made
    self._loop.create_task(res)
Traceback (most recent call last):
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\asyncio\run.py", line 89, in _server_callback
    await TCPServer(app, loop, config, reader, writer)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\asyncio\tcp_server.py", line 75, in run
    await self._read_data()
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\asyncio\tcp_server.py", line 102, in _read_data
    await self.protocol.handle(RawData(data))
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\protocol\__init__.py", line 63, in handle
    return await self.protocol.handle(event)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\protocol\h11.py", line 108, in handle
    await self._handle_events()
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\protocol\h11.py", line 168, in _handle_events
    await self.stream.handle(event)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\protocol\ws_stream.py", line 195, in handle
    self.connection.receive_data(event.data)
AttributeError: 'WSStream' object has no attribute 'connection'

使用的均为最新版本

**Comment by amongtheflowers** [comment]
好像是hypercorn的版本问题，我用的hypercorn0.9.1，aiocqhttp1.2.2, nonebot 1.4.2能正常跑

**Comment by nainiu233** [comment]
降低了版本 还是不行
Task exception was never retrieved
future: <Task finished coro=<worker_serve.<locals>._server_callback() done, defined at C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\asyncio\run.py:88> exception=AttributeError("'WSStream' object has no attribute 'connection'") created at C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\asyncio\streams.py:239>
source_traceback: Object created at (most recent call last):
  File "C:/Users/lpj15/Desktop/酷Q Air/awesome-bot/bot.py", line 13, in <module>
    nonebot.run()
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\nonebot\__init__.py", line 105, in run
    get_bot().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\nonebot\__init__.py", line 54, in run
    super().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\aiocqhttp\__init__.py", line 200, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\quart\app.py", line 1615, in run
    loop.run_until_complete(task)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 570, in run_until_complete
    self.run_forever()
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 538, in run_forever
    self._run_once()
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 1774, in _run_once
    handle._run()
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\asyncio\streams.py", line 239, in connection_made
    self._loop.create_task(res)
Traceback (most recent call last):
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\asyncio\run.py", line 89, in _server_callback
    await TCPServer(app, loop, config, reader, writer)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\asyncio\tcp_server.py", line 75, in run
    await self._read_data()
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\asyncio\tcp_server.py", line 102, in _read_data
    await self.protocol.handle(RawData(data))
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\protocol\__init__.py", line 63, in handle
    return await self.protocol.handle(event)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\protocol\h11.py", line 108, in handle
    await self._handle_events()
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\protocol\h11.py", line 168, in _handle_events
    await self.stream.handle(event)
  File "C:\Users\lpj15\AppData\Local\Programs\Python\Python37\lib\site-packages\hypercorn\protocol\ws_stream.py", line 195, in handle
    self.connection.receive_data(event.data)
AttributeError: 'WSStream' object has no attribute 'connection'
[2020-03-06 19:26:15,997] 127.0.0.1:64817 GET /ws/event/ 1.1 101 - 28336
[2020-03-06 19:26:16,003] 127.0.0.1:64816 GET /ws/api/ 1.1 101 - 29597

**Comment by nainiu233** [comment]
不知道什么情况自己好了 只报
[2020-03-07 20:48:02,162] INFO in __init__: received event: message.private.friend
可能是我自己的问题 关闭了

**Comment by richardchien** [comment]
这个问题确实存在，抽空会修，issue 先开着

**Comment by nainiu233** [comment]
有什么补救发放吗？

**Comment by richardchien** [comment]
@nainiu233 快了快了

**Comment by richardchien** [comment]
试下 CQHTTP 更新到最新版（v4.14.1）看看，应该是解决了，nonebot 和 aiocqhttp 等依赖都可以直接装最新的

**Comment by nainiu233** [comment]
ok 没有问题了 谢谢
