### ISSUE TITLE
使用scheduler发送消息时出现ApiNotAvailable错误

### ISSUE THREAD

**Issue by raymond-coulson** [richardchien/nonebot#158]
我使用原本使用的是aiocqhttp库，然后我利用asyncioscheduler写了一个定时发送功能，结果在发送时出现ApiNotAvailable错误，然后我转战到了nonebot，希望他的scheduler能解决问题，但是还是出现了相同的错误。于此同时，bot还是能正常处理on_message事件的消息
问题代码：

```
@nonebot.scheduler.scheduled_job('interval', seconds=600)
async def fiveMinTimer():
    soul.ResetMemory()
    print("问题重置完成！")
    alarms = checkSchedule()
    if alarms:
        for group in allowGroup:
            for alarm in alarms:
                await bot.send_group_msg(group_id = group,message = alarm)
```

得到的异常：

```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\site-packages\apscheduler\executors\base_py3.py", line 29, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "c:\Users\coulson\Desktop\Boss\main.py", line 107, in fiveMinTimer
    await bot.send_group_msg(group_id = group,message = alarm)
  File "C:\Program Files\Python37\lib\site-packages\aiocqhttp\api.py", line 184, in call_action
    raise ApiNotAvailable
```

我查看了一下，发现这个异常是由于没有成功连接到ws导致的，但是定时中调用的bot对象难道不是我run的那个bot对象吗？

**Comment by yp05327** [comment]
更新了最新版本的aiocqhttp和nonebot之后就没这个问题了
但是我原本在启动时会执行一个异步函数 更新之后就不会自动执行这个异步操作了
所以有没有什么方法可以在启动时让他自动执行一个异步函数
我现在用的是ensure_future 并不会被执行

**Comment by richardchien** [comment]
> 所以有没有什么方法可以在启动时让他自动执行一个异步函数
> 我现在用的是ensure_future 并不会被执行

现在 nonebot 有个 [`on_startup` 装饰器](https://nonebot.cqp.moe/api.html#decorator-on-startup)，可以看看
