### ISSUE TITLE
通过Pyinstaller 打包 报错

### ISSUE THREAD

**Issue by oneforgit** [richardchien/nonebot#43]
bot机器人通过pyinstaller 打包，会报WinError 3
请作者帮忙看一下：

------
Traceback (most recent call last):
  File "bot.py", line 6, in <module>
  File "site-packages\nonebot\plugin.py", line 72, in load_builtin_plugins
  File "site-packages\nonebot\plugin.py", line 48, in load_plugins
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\king\\AppData\\Local\\Temp\\4\\_MEI23356\\nonebot\\plugins'
[18796] Failed to execute script bot

**Comment by richardchien** [comment]
你看一下 `C:\Users\king\AppData\Local\Temp\4\_MEI23356\nonebot\plugins` 这个文件夹到底在不在？感觉上应该是你虚拟环境没配对？

**Comment by oneforgit** [comment]
没有用虚拟环境，所有的包全部安装在本地，不过我的python是安装的是Anaconda3 发行版本，有影响吗？
你电脑上能打包成功吗？

> pyinstaller -F c:/xxxx/instance/bot.py

**Comment by amongtheflowers** [comment]
可以hidden或者在py文件里面import，然后重新打包

**Comment by amongtheflowers** [comment]
还有指定数据文件夹才可以
