### ISSUE TITLE
get_group_member_list()方法在酷Q pro更新至5.14.9之后不可用

### ISSUE THREAD

**Issue by VSakuya** [richardchien/nonebot#87]
错误信息：
[2019-07-04 13:45:29,090 nonebot] ERROR: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/nonebot/command/__init__.py", line 627, in _real_run_command
    await asyncio.wait_for(future, timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 388, in wait_for
    return await fut
  File "/usr/local/lib/python3.7/dist-packages/nonebot/command/__init__.py", line 118, in run
    await self.func(session)
  File "/root/coolq/nonebot/asset/plugins/test.py", line 24, in _
    g_list = await bot.get_group_member_list(group_id = 204421130)
  File "/usr/local/lib/python3.7/dist-packages/aiocqhttp/api.py", line 170, in call_action
    action, **params)
  File "/usr/local/lib/python3.7/dist-packages/aiocqhttp/api.py", line 140, in call_action
    return _handle_api_result(await ResultStore.fetch(seq))
  File "/usr/local/lib/python3.7/dist-packages/aiocqhttp/api.py", line 39, in _handle_api_result
    raise ActionFailed(retcode=result.get('retcode'))
aiocqhttp.exceptions.ActionFailed

**Comment by VSakuya** [comment]
貌似所有的get方法都坏了，应该是http api跟新版酷q不兼容，我的暂时解决方法：用旧版的酷Q bin文件夹里的libeay32.dll和zlib1.dll替换掉新的，就正常了。

**Comment by richardchien** [comment]
@VSakuya 打印一下抛出的异常的 retcode 属性看看错误码是多少

**Comment by VSakuya** [comment]
> 
> 
> @VSakuya 打印一下抛出的异常的 retcode 属性看看错误码是多少
在尝试打出错误码的时候，我发现这个bug竟然没了！同样的代码，同样的三台不同地域不同网络的服务器，同样的账号！打扰你了作者。
