### ISSUE TITLE
框架中似乎存在编码问题？（最新nonebot版本）

### ISSUE THREAD

**Issue by aboutmydreams** [richardchien/nonebot#88]
[2019-07-08 00:17:46,006 nonebot] DEBUG: Not a known command, ignored
Call stack:
  File "bothao.py", line 14, in <module>
    nonebot.run(host='127.0.0.1', port=8080)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\__init__.py", line 105, in run
    get_bot().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\__init__.py", line 54, in run
    super().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiocqhttp\__init__.py", line 228, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quart\app.py", line 1346, in run
    run_single(self, config, loop=loop)  # type: ignore
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hypercorn\asyncio\run.py", line 126, in run_single
    loop.run_until_complete(worker_serve(app, config))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 555, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 523, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1758, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\message.py", line 21, in handle_message
    _log_message(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\message.py", line 118, in _log_message
    logger.info(f'Self: {ctx["self_id"]}, '
Message: 'Self: 3539347852, Message 322870 from 2854196306@[Ⱥ:310124457]: [CQ:at,qq=2513865051] ▒▒▒▒▒▒Ϸ▒▒▒▒▒ؼ▒ʱ▒▒▒أ▒һ▒▒▒▒▒▒▒▒˵▒▒\U0001f609Ҫ▒ǲ▒֪▒▒▒㻭▒Ҳ▒▒▒ô▒棬▒▒▒▒▒▒▒ҡ▒▒▒ô▒桱'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f609' in position 99: illegal multibyte sequence
Call stack:
  File "bothao.py", line 14, in <module>
    nonebot.run(host='127.0.0.1', port=8080)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\__init__.py", line 105, in run
    get_bot().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\__init__.py", line 54, in run
    super().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiocqhttp\__init__.py", line 228, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quart\app.py", line 1346, in run
    run_single(self, config, loop=loop)  # type: ignore
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hypercorn\asyncio\run.py", line 126, in run_single
    loop.run_until_complete(worker_serve(app, config))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 555, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 523, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1758, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\message.py", line 39, in handle_message
    handled = await handle_command(bot, ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\command\__init__.py", line 516, in handle_command
    cmd, current_arg = parse_command(bot, str(ctx['message']).lstrip())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\command\__init__.py", line 443, in parse_command
    logger.debug(f'Parsing command: {cmd_string}')
Message: 'Parsing command: [CQ:at,qq=2513865051] ▒▒▒▒▒▒Ϸ▒▒▒▒▒ؼ▒ʱ▒▒▒أ▒һ▒▒▒▒▒▒▒▒˵▒▒\U0001f609Ҫ▒ǲ▒֪▒▒▒㻭▒Ҳ▒▒▒ô▒棬▒▒▒▒▒▒▒ҡ▒▒▒ô▒桱'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f60f' in position 134: illegal multibyte sequence
Call stack:
  File "bothao.py", line 14, in <module>
    nonebot.run(host='127.0.0.1', port=8080)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\__init__.py", line 105, in run
    get_bot().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\__init__.py", line 54, in run
    super().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\aiocqhttp\__init__.py", line 228, in run
    self._server_app.run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\quart\app.py", line 1346, in run
    run_single(self, config, loop=loop)  # type: ignore
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\hypercorn\asyncio\run.py", line 126, in run_single
    loop.run_until_complete(worker_serve(app, config))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 555, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 523, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\base_events.py", line 1758, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\message.py", line 21, in handle_message
    _log_message(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\message.py", line 118, in _log_message
    logger.info(f'Self: {ctx["self_id"]}, '
Message: 'Self: 3539347852, Message 322884 from 2854196306@[Ⱥ:310124457]: [CQ:at,qq=1004218112] ▒ղ▒▒▒▒▒▒▒▒һ▒▒\U0001f60f▒▒▒뵽▒▒▒»▒▒▒▒▒▒▒▒▒Ӧ▒ö▒▒˰▒'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\logging\__init__.py", line 985, in emit
    stream.write(msg)
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f60f' in position 88: illegal multibyte sequence
Call stack:
  File "bothao.py", line 14, in <module>
    nonebot.run(host='127.0.0.1', port=8080)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\__init__.py", line 105, in run
    get_bot().run(host=host, port=port, *args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\nonebot\__init__.py", line 54, in run
    super().run(host=host, port=port, *args, **kwargs)

**Comment by uu9** [comment]
sys.stdout不是Unicode的
换个能显示Unicode的终端吧
我也遇到这个问题了。。。

**Comment by aboutmydreams** [comment]
好的 谢谢
